=== corriol/mlims/assets/02/bookmarks.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="bookmarks">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="website" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>            
              <xs:element name="name" type="xs:string"/>
              <xs:element name="description" type="xs:string"/>
              <xs:element name="url" type="xs:anyURI"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== corriol/mlims/assets/02/bookmarks.xml
<?xml version="1.0" encoding="UTF-8"?>
<bookmarks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="bookmarks.xsd">
    <website>
        <name>Abrirllave</name>
        <description>Tutoriales de inform√°tica.</description>
        <url>http://www.abrirllave.com/</url>
    </website>
    <website>
        <name>Wikipedia</name>
        <description>La enciclopedia libre.</description>
        <url>http://www.wikipedia.org/</url>
    </website>
    <website>
        <name>W3C</name>
        <description>World Wide Web Consortium.</description>
        <url>http://www.w3.org/</url>
    </website>
</bookmarks>
